### ISSUE TITLE
[AnVIL DX] Make searches sharable in browser address bar

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#677] opened 2023-02-02 17:57 UTC
#### Need 
Users need to be able to share links for queries. 

#### Approach
In general, when a  filter is selected, we need to add the filter to the address bar so that if the link is copied and then visited  the same filter is applied to the search results.

This should contain the selected entity, as well as the filters. (entity is for free as its in the URL path)

1. For the Azul browsers, we need to use the current Azul format.
2. For the catalogs, we can use the current format from the AnVIL dataset catalog. 

#### DOD
Users can share links that contain the selected entity and any applied filters. (Sharing of sort and selected columns can come on separate tickets)

**Comment by MillenniumFalconMechanic** [comment] 2023-05-02 20:12
Dupe of https://github.com/clevercanary/data-browser/issues/829.

**Closed by MillenniumFalconMechanic** 2023-05-02 20:12 UTC
