### ISSUE TITLE
[NCPI] For catalogs, allow download of current result set as a CSV

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#678] opened 2023-02-02 18:00 UTC
Similar to how the current AnVIL dataset catalog works.

```[tasklist]
### Tasks
- [ ] https://github.com/clevercanary/cc-design/issues/21
- [ ] https://github.com/clevercanary/data-browser/issues/803
```

**Comment by MillenniumFalconMechanic** [comment] 2023-05-02 23:28
Dupe of https://github.com/clevercanary/data-browser/issues/803.

**Closed by MillenniumFalconMechanic** 2023-05-02 23:28 UTC
