### ISSUE TITLE
[HCA DB] Update HCA/LungMAP edit columns configuration

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [clevercanary/data-browser#156] opened 2022-06-28 20:29 UTC

**Comment by frano-m** [comment] 2023-11-08 08:29
Add in all available columns as optional.

**Comment by frano-m** [comment] 2024-03-15 04:23
Duplicate of https://github.com/DataBiosphere/data-browser/issues/3944.

**Closed by frano-m** 2024-03-15 04:23 UTC
